{{- $isEnabled := .Values.airflow.isDataPartitionDeployment | default false -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-log-processor
  namespace: osdu
  labels:
    app: airflow-log-processor
spec:
  selector:
    matchLabels:
      app: airflow-log-processor
  template:
    metadata:
      labels:
        app: airflow-log-processor
        aadpodidbinding: "osdu-identity"
    spec:
      containers:
      - name: airflow-log-processor
        image: {{ .Values.image.repository }}/airflow-function-{{ .Values.image.branch }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        env:
          - name: AzureFunctionsJobHost__functions__0
            value: queueTrigger
          - name: FUNCTIONS_WORKER_RUNTIME
            value: dotnet
          - name: AzureLogWorkspaceLogName
            value: airflow_dag
          - name: AzureLogWorkspaceCustomerId
            valueFrom:
              secretKeyRef:
                name: {{ .Values.logAnalytics.workspaceId.secretName }}
                key: {{ .Values.logAnalytics.workspaceId.secretKey }}
          - name: AzureLogWorkspaceSharedKey
            valueFrom:
              secretKeyRef:
                name: {{ .Values.logAnalytics.workspaceKey.secretName }}
                key: {{ .Values.logAnalytics.workspaceKey.secretKey }}
          - name: AzureWebJobsStorage
            valueFrom:
              secretKeyRef:
                name: airflow
                key: storage-connection
        
---
{{ if $isEnabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
  namespace: osdu
spec:
  podIdentity:
    provider: azure
{{ else }}
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-queue-auth
  namespace: osdu
spec:
  podIdentity:
    provider: azure
{{ end }}

---
{{ if $isEnabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-queue-scaledobject
  namespace: osdu
spec:
  scaleTargetRef:
    name: azurequeue-function
  triggers:
  - type: azure-queue
    metadata:
      # Required
      queueName: airflowlogqueue
      # Optional
      queueLength: "5" # default 5
    authenticationRef:
        name: azure-queue-auth # authenticationRef would need either podIdentity or define a connection parameter
{{ else }}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-queue-scaledobject
  namespace: osdu
spec:
  scaleTargetRef:
    deploymentName: azurequeue-function
  triggers:
  - type: azure-queue
    metadata:
      # Required
      queueName: airflowlogqueue
      # Optional
      queueLength: "5" # default 5
    authenticationRef:
        name: azure-queue-auth # authenticationRef would need either podIdentity or define a connection parameter
{{ end }}