{{- $isEnabled := .Values.airflow.isDataPartitionDeployment | default false -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  {{ if $isEnabled }}
  name: {{ .Release.Namespace }}-airflowdagpv
  labels:
    usage: {{ .Release.Namespace }}-airflow-dag
  {{ else }}
  name: airflowdagpv
  labels:
    usage: airflow-dag
  {{ end }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  azureFile:
    secretName: airflow
    shareName: airflowdags
  volumeMode: Filesystem
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflowdagpvc
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      {{ if $isEnabled }}
      usage: {{ .Release.Namespace }}-airflow-dag
      {{ else }}
      usage: airflow-dag
      {{ end }}