{{- $isEnabled := .Values.airflow.isDataPartitionDeployment | default false -}}
{{ if $isEnabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  secretObjects:
  - secretName: airflow
    type: Opaque
    data:
    - objectName: airflow-storage
      key: storage-account
    - objectName: airflow-storage-key
      key: storage-key
    - objectName: airflow-storage-connection
      key: storage-connection
    - objectName: airflow-remote-log-connection
      key: remote-log-connection
    - objectName: airflow-admin-password
      key: admin-password
    - objectName: airflow-fernet-key
      key: fernet-key
    - objectName: airflow-storage
      key: azurestorageaccountname
    - objectName: airflow-storage-key
      key: azurestorageaccountkey
  - secretName: postgres
    type: Opaque
    data:
    - objectName: "postgres-password"
      key: postgres-password
  - secretName: redis
    type: Opaque
    data:
    - objectName: "redis-queue-password"
      key: redis-queue-password
  - secretName: dp-logging
    type: Opaque
    data:
    - objectName: "log-workspace-id"
      key: workspace-id
    - objectName: "log-workspace-key"
      key: workspace-key
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    resourceGroup: "{{ .Values.azure.resourcegroup }}"
    keyvaultName: "{{ .Values.azure.keyvault }}"
    subscriptionId: "{{ .Values.azure.subscription }}"
    tenantId: "{{ .Values.azure.tenant }}"
    objects: |
      array:
        - |
          objectName: airflow-storage
          objectType: secret
        - |
          objectName: airflow-storage-connection
          objectType: secret
        - |
          objectName: airflow-remote-log-connection
          objectType: secret
        - |
          objectName: airflow-storage-key
          objectType: secret
        - |
          objectName: airflow-admin-password
          objectType: secret
        - |
          objectName: airflow-fernet-key
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: redis-queue-password
          objectType: secret
        - |
          objectName: log-workspace-id
          objectType: secret
        - |
          objectName: log-workspace-key
          objectType: secret
{{ end }}
