#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: airflow
  namespace: {{ .Values.airflow.kubernetesPodOperator.namespace }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - create
      - get
      - delete
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
      - get

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: airflow
  namespace: {{ .Values.airflow.kubernetesPodOperator.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow
subjects:
  - kind: ServiceAccount
    name: {{ .Values.airflow.serviceAccount.name }}
    {{- $isEnabled := .Values.airflow.isDataPartitionDeployment | default false -}}
    {{ if $isEnabled }}
    namespace: {{ .Release.Namespace}}
    {{ else }}
    namespace: osdu
    {{ end }}
