version: '3'
services:
  partition-data-init:
    build:
      context: ../
      dockerfile: ./partition_init/Dockerfile
    image: msosdu.azurecr.io/partition-data-init:$VERSION
    environment:
      OSDU_HOST: $OSDU_HOST
      PARTITIONS: $PARTITIONS # comma separated list of partitions
      VERSION: $VERSION