#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


parameters:
  providers: []
  serviceName: ""
  skipDeploy: false
  hldRegPath: "providers/azure/hld-registry"
  checkoutRepo: self
  extractedChartFolder: "templates"
  installThroughHelm: false
  isDPDeployment: false
  DPName: ""
  namespace: ""
  addDPNameToService: false

stages:
  - ${{ each provider in parameters.providers }}:
    - ${{ each environment in provider.environments }}:
      - stage: 'Deploy_${{ provider.name }}_${{ environment }}_${{ parameters.serviceName }}'

        variables:
          - group: '${{ provider.name }} Target Env Secrets - ${{ environment }}'
          - group: '${{ provider.name }} Target Env - ${{ environment }}'
          - ${{ if eq(parameters.isDPDeployment, 'true') }}:
            - group: '${{ provider.name }} Target Env Data Partition ${{ parameters.DPName }} - ${{ environment }}'
            - group: '${{ provider.name }} Target Env Data Partition ${{ parameters.DPName }} Secrets - ${{ environment }}'


        jobs:
        - deployment: Deploy
          pool:
            name: $(AGENT_POOL)
          environment: ${{ environment }}
          strategy:
            runOnce:
              deploy:
                steps:
                - download: none

                - template: tasks/aks-deployment-steps.yml
                  parameters:
                    ${{ if and(eq(parameters.isDPDeployment, 'true'), eq(parameters.addDPNameToService, 'true')) }}:
                      serviceName: "${{ parameters.DPName }}-${{ parameters.serviceName }}"
                    ${{ if or(eq(parameters.isDPDeployment, 'false'), eq(parameters.addDPNameToService, 'false')) }}:
                      serviceName: ${{ parameters.serviceName }}
                    providerName: ${{ provider.name }}
                    environment: ${{ environment }}
                    chartPath: ${{ parameters.chartPath }}
                    valuesFile: ${{ parameters.valuesFile }}
                    skipDeploy: ${{ parameters.skipDeploy }}
                    hldRegPath: ${{ parameters.hldRegPath }}
                    checkoutRepo: ${{ parameters.checkoutRepo }}
                    chartModificationScript: ${{ parameters.chartModificationScript }}
                    extractedChartFolder: ${{ parameters.extractedChartFolder }}
                    installThroughHelm: ${{ parameters.installThroughHelm }}
                    ${{ if eq(parameters.isDPDeployment, 'true') }}:
                      baseNameRG: $(base-name-dp)
                    namespace: ${{ parameters.namespace }}

                - template: tasks/flux-chart-wait.yml
                  parameters:
                    serviceName: ${{parameters.serviceName}}
                    skipCheck: ${{ parameters.skipCheck }}
                    environment: ${{ environment }}
                    imageRepoName: '${{ parameters.serviceName }}'
