#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Required Group Variables - `Infrastructure Pipeline Variables`
  # AGENT_POOL
  # AZURE_REGISTRY
  # HELM_REPO
  # K8_ENV_PREFIX


trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - /charts/osdu-common/*
      - /devops/osdu-common-pipeline.yml
    exclude:
      - /**/*.md

pr:
  autoCancel: false
  branches:
    include:
      - "*"
    exclude:
      - master
  paths:
    include:
      - /charts/osdu-common/*
      - /devops/osdu-common-pipeline.yml
    exclude:
      - /**/*.md

resources:
  repositories:
  - repository: K8ManifestsRepo
    type: git
    name: k8-gitops-manifests

variables:
  - group: 'Azure Common Secrets'
  - group: 'Azure - Common'

  - name: 'MANIFEST_REPO'
    value: $[ resources.repositories['K8ManifestsRepo'].name ]
  - name: 'HELM_VERSION'
    value: '3.3.0'
  - name: 'HELM_CHART_PATH'
    value: 'charts/osdu-common'
  - name: 'MANIFEST_GENERATION_PATH'
    value: 'generated'
  - name: generateName
    value: "osdu-common"

stages:
  - template: tasks/aks-deploy-stages.yml
    parameters:
      generateName: ${{ variables.generateName }}
      providers:
        - name: Azure
          environments: ["dev"]
