stages:
  - validate
  - build
  - unit-test
  - service-resource

validate:
    stage: validate
    script: 
        - echo "validate script"

cr-unit-test:
    stage: test
    script:
        - echo "unit test cr"

cr-plan:
    stage: build
    script:
        - echo "cr plan"

sr-unit-test:
    stage: test
    script:
        - echo "unit test sr"
        
sr-plan:
    stage: build
    script:
        - echo "sr plan"

dr-unit-test:
    stage: test
    script:
        - echo "unit test dr"

dr-plan:
    stage: build
    script:
        - echo "dr plan"
