image:
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/0.12:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json
  TF_VERSION: 0.14.4 
  GO_VERSION: 1.12.14
  TEMPLATE: samples/webdata
  TEST_CASE: testWebData

cache:
  paths:
    - .terraform


stages:
  - validate
  - build
  - unit-test
  
include:
  - 'devops/premerge_pipeline/.tf-plan.yml'
  - 'devops/premerge_pipeline/.unit-test.yml'
  - 'devops/premerge_pipeline/.validate.yml'

validate:
  extends: .validate

cr-unit-test:
  variable:
    TEST_SUITE_NAME: centralUnitTest
  extends: .unit-test

cr-plan:
  extends: .tf-plan

sr-unit-test:
  variable:
    TEST_SUITE_NAME: servicelUnitTest
  extends: .unit-test

sr-plan:
  extends: .tf-plan

dr-unit-test:
  variable:
    TEST_SUITE_NAME: partitionUnitTest
  extends: .unit-test

dr-plan:
  extends: .tf-plan
