variables:
  TF_VERSION: 0.14.4
  GO_VERSION: 1.12.14

stages:
  - validate
  - build
  - unit-test

image:
  name: hashicorp/terraform:$TF_VERSION
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

include:
  - 'devops/gitlab/.tf-plan.yml'
  - 'devops/gitlab/.go-lint.yml'
  - 'devops/gitlab/.tf-lint.yml'
  - 'devops/gitlab/.unit-test.yml'

tf-lint:
  extends: .tf-lint

go-lint:
  extends: .go-lint

cr-unit-test:
  extends: .unit-test

cr-plan:
  extends: .tf-plan

sr-unit-test:
  extends: .unit-test

sr-plan:
  extends: .tf-plan

dr-unit-test:
  extends: .unit-test

dr-plan:
  extends: .tf-plan
