
stages:
  - validate
  - common-resource
  - data-resource
  - service-resource

validate:
    stage: validate
    script: 
        - echo "validate script"

cr-unit-test:
    stage: common-resource
    script:
        - echo "unit test cr"

cr-plan:
    stage: common-resource
    script:
        - echo "cr plan"

sr-unit-test:
    stage: service-resource
    script:
        - echo "unit test sr"
        
sr-plan:
    stage: service-resource
    script:
        - echo "sr plan"

dr-unit-test:
    stage: data-resource
    script:
        - echo "unit test dr"

dr-plan:
    stage: data-resource
    script:
        - echo "dr plan"
