image:
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/0.12:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_VERSION: 0.14.4 
  GO_VERSION: 1.12.14

cache:
  paths:
    - .terraform

stages:
  - validate
  - build
  - unit-test
  
include:
  - 'devops/premerge_pipeline/.tf-plan.yml'
  - 'devops/premerge_pipeline/.unit-test.yml'
  - 'devops/premerge_pipeline/.validate.yml'

validate:
  extends: .validate

cr-unit-test:
  variables:
    TEST_SUITE_NAME: centralUnitTest
  extends: .unit-test

cr-plan:
  extends: .tf-plan

sr-unit-test:
  variables:
    TEST_SUITE_NAME: serviceUnitTest
    TF_VAR_ssh_public_key_file: ""
    TF_VAR_gitops_ssh_url: ""
    TF_VAR_gitops_ssh_key_file: ""
  extends: .unit-test

sr-plan:
  extends: .tf-plan

dr-unit-test:
  variables:
    TEST_SUITE_NAME: partitionUnitTest
    TF_VAR_elasticsearch_endpoint: ""
    TF_VAR_elasticsearch_username: ""
    TF_VAR_elasticsearch_password: ""
  extends: .unit-test

dr-plan:
  extends: .tf-plan
