version: '3'
services:
  data-seeding-agent:
    build:
      context: ../
      dockerfile: ./data_seeding_agent/Dockerfile
    image: msosdu.azurecr.io/data-seeding-agent:$VERSION
    environment:
      TENANT_ID: $TENANT_ID
      PRINCIPAL_ID: $PRINCIPAL_ID
      PRINCIPAL_SECRET: $PRINCIPAL_SECRET
      PARTITION_NAME_ARRAY: $PARTITION_NAME_ARRAY # comma separated list of partitions
      RESOURCE_GROUP_NAME: $RESOURCE_GROUP_NAME
      VERSION: $VERSION