apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: osdu
data:
  airflow: "1"
  partition: "2"
  entitlements-azure: "3"
  legal: "4"
  storage: "5"
  indexer-service: "6"
  search-service: "7"
  entitlements: "8"
  seismic-dms: "9"
