apiVersion: apps/v1
kind: Deployment
metadata:
  name: appinsights-statsd
  labels:
    app: appinsights-statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appinsights-statsd
  template:
    metadata:
      labels:
        app: appinsights-statsd
    spec:
      containers:
      - name: appinsights-statsd
        image: binroon/appinsights-statsd:latest
        imagePullPolicy: Always
        command: ["node"]
        args: ["/usr/src/app/statsd/stats.js", "/usr/src/app/statsd/backends/config/appinsightsconfig.js"]
        volumeMounts:
          - name: config-volume
            mountPath: /usr/src/app/statsd/backends/config
        env:
          - name: APPLICATION_INSIGHTS_INSTRUMENTATION_KEY
            valueFrom:
              secretKeyRef:
                name: appinsights-statsd-ikey
                key: APPLICATION_INSIGHTS_INSTRUMENTATION_KEY
        ports:
          - containerPort: 8125
            protocol: UDP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
        - name: config-volume
          configMap: 
            name: airflow-appinsight-statsd-config
---
apiVersion: v1
kind: Service
metadata:
  name: appinsights-statsd
spec:
  type: LoadBalancer
  ports:
  - port: 8125
    protocol: UDP
  selector:
    app: appinsights-statsd
---
apiVersion: v1
kind: Pod
metadata:
  name: appinsights-statsd-test-client
spec:
  containers:
  - name: appinsights-statsd-test-client
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
