#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

steps:
  - task: Bash@3
    name: GenerateHelmTemplate
    displayName: Helm Template
    env:
      CHART_PATH: ${{parameters.chartPath}}
      VALUES_FILE: ${{parameters.valuesFile}}
      SERVICE_NAME: ${{parameters.serviceName}}
      GENERATION_PATH: ${{parameters.generationPath}}
      BRANCH: $(Build.SourceBranchName)
      TAG: $(Build.SourceVersion)
    inputs:
      targetType: 'inline'
      script: |
        #!/usr/bin/env bash

          cd $(Build.SourcesDirectory)/$(Build.Repository.Name)

          echo "Making a Directory... --> $CHART_PATH/$GENERATION_PATH"
          mkdir $CHART_PATH/$GENERATION_PATH
          cat $(Build.SourcesDirectory)/$(Build.Repository.Name)/${{parameters.chartPath}}/values.yaml

          ls -l $(Build.SourcesDirectory)/$(Build.Repository.Name)

          echo "Extracting Manifest"
          helm template $SERVICE_NAME $CHART_PATH -f $(Build.SourcesDirectory)/$(Build.Repository.Name)/${{parameters.chartPath}}/values.yaml --output-dir $CHART_PATH/$GENERATION_PATH
