parameters:
  stepName: ''
  runPythonTest: ''
  testPythonFilePath: ''
  testPythonFile: ''
  testArtifactLocation: 'drop/deploy'

steps:
  - task: UsePythonVersion@0
    condition: and(succeeded(), eq('${{ parameters.runPythonTest }}', 'true'))
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: Bash@3
    condition: and(succeeded(), eq('${{ parameters.runPythonTest }}', 'true'))
    name: ${{ parameters.stepName }}
    displayName: 'Python run integration tests'
    env:
      VIRTUAL_SERVICE_HOST_NAME: $(DNS_HOST)
      AZURE_TENANT_ID: $(AZURE_TENANT_ID)
      INTEGRATION_TESTER: $(INTEGRATION_TESTER)
      AZURE_TESTER_SERVICEPRINCIPAL_SECRET: $(AZURE_TESTER_SERVICEPRINCIPAL_SECRET)
      AZURE_AD_APP_RESOURCE_ID: $(AZURE_AD_APP_RESOURCE_ID)
      MY_TENANT: $(MY_TENANT)
    inputs:
      targetType: 'inline'
      workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.testArtifactLocation }}/${{ parameters.testPythonFilePath }}'
      script: |
        #!/usr/bin/env bash
        chmod +x ./run-integration-tests.sh
        ./run-integration-tests.sh
        exit $?
