parameters:
  stepName: ''
  runPythonTest: ''
  testPythonFilePath: ''
  testPythonFile: ''
  testArtifactLocation: 'drop/deploy'

steps:
  - task: Bash@3
    condition: and(succeeded(), eq('${{ parameters.runPythonTest }}', 'true'))
    name: ${{ parameters.stepName }}
    displayName: 'Run python integration tests'
    inputs:
      targetType: filePath
      filePath: '$(System.DefaultWorkingDirectory)/${{ parameters.testArtifactLocation }}/${{ parameters.testPythonFilePath }}/${{ parameters.testPythonFile }}'
      arguments: '$(AUTH_SECRET) $(AUTH_SERVICE_TOKEN_X_API_KEY)'
      workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.testArtifactLocation }}/${{ parameters.testPythonFilePath }}'
    env:
      VIRTUAL_SERVICE_HOST_NAME: $(DNS_HOST)
      INTEGRATION_TESTER: $(INTEGRATION_TESTER)
      AZURE_TESTER_SERVICEPRINCIPAL_SECRET: $(AZURE_TESTER_SERVICEPRINCIPAL_SECRET)
      AZURE_AD_TENANT_ID: $(AZURE_AD_TENANT_ID)
      AZURE_AD_APP_RESOURCE_ID: $(AZURE_AD_APP_RESOURCE_ID)
      BASE_URL: /api/unit
      MY_TENANT: $(MY_TENANT)
