

.unit-test:
    variables:
        TEST_SUITE_NAME: ""
    stage: unit-test
    image:
        name: "golang:${GO_VERSION}-alpine"
        entrypoint:
        - "/usr/bin/env"
        - "PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    script:
        - currdir=$(pwd)
        - apk add --no-cache gcc libc-dev bind-tools git
        - go get -u -d github.com/magefile/mage
        - magedir=$(find /go/pkg/mod/ -name magefile -type d | grep -v cache)
        - cd $magedir/$(ls $magedir/)
        - go run bootstrap.go
        - cd $currdir/infra
        - mage ${TEST_SUITE_NAME}
