.unit-test:

    stage: unit-test
    image:
        name: "golang:${GO_VERSION}-alpine"
        entrypoint:
        - "/usr/bin/env"
        - "PATH=/go/bin:/usr/local/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    script:
        - currdir=$(pwd)
        - cd /tmp
        - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O terraform.zip
        - unzip terraform.zip -d /usr/bin
        - cd $currdir
        - terraform version
        - (if [[ "$(go version)" == "go version go${GO_VERSION} linux/amd64" ]]; then echo "✓ Go binary installed!"; else echo "Go binary not installed!"; /bin/false; fi);
        - (if [[ "$(terraform version)" == "Terraform v0.14.4" ]]; then echo "✓ Terrafrom binary installed!"; else echo "Terraform binary not installed!"; /bin/false; fi);
        - echo "Terraform workspace ${TF_WORKSPACE}"
        - currdir=$(pwd)
        - apk add --no-cache gcc libc-dev bind-tools git
        - go get -u -d github.com/magefile/mage
        - magedir=$(find /go/pkg/mod/ -name magefile -type d | grep -v cache)
        - cd $magedir/$(ls $magedir/)
        - go run bootstrap.go
        - cd $currdir/infra
        - mage centralUnitTest
